config/routes.rb
Nguoidep::Application.routes.draw do

  resources :issues, only: [:show], constraints: {id: /[0-9]+/} do
    scope :format => true, :constraints => { :format => 'json' } do
      resources :pages, only: [:index, :show], constraints: {id: /[0-9]+/}
    end
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
             controllers: {
                 :registrations => "registrations",
                 :confirmations => "confirmations",
                 :passwords => "passwords"
             }

  #devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
  #                   controllers: {:registrations => "registrations"}

  Devise.router_name = :main_app

  root to: 'home#index'
  get "/contact",     to: "home#contact"
  get "/advertising", to: "home#advertising"

  #resque_constraint = lambda do |request|
  #  request.env['warden'].authenticate? and request.env['warden'].user.role? :admin
  #end

  #constraints resque_constraint do
  #  mount Resque::Server, :at => "/admin/jobs"
  #end

  namespace :admin do
    resources :users

    resources :issues do
      resources :pages
    end

    resources :companies
  end

  #get :admin, to: "admin/authentications#index"

  namespace :api do
    resources :issues, constraints: {id: /[0-9]+/},    defaults: { format: 'json' }
    resources :pages, only: [:create, :show, :update], defaults: { format: 'json' }
  end

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :date, :title
  attr_accessible :date, :title, as: :admin

  has_many :pages, dependent: :destroy, order: "page_nr ASC"

  scope :latest, order("date DESC").limit(1)

  def self.all_issues_with_id
    order("date DESC").map { |issue| [issue.title + ' -- ' + issue.date.to_s, issue.id, ] }
  end

  def first_pages
    pages.order("page_nr ASC").limit(5)
  end

  # Return array of
  def companies
    #sql = "select distinct c.name
    #       from (issues as i inner join pages as p on i.id=p.issue_id)
    #       inner join ads as a on p.id=a.page_id
    #       inner join companies as c on a.company_id=c.id
    #       where i.id = #{id};"
    Issue.select("companies.id, companies.name")
         .joins(pages: {ads: :company})
         .where("issues.id=#{id}")
         .order("companies.name ASC")
         .uniq
         .map{|c| [c.name, c.id] }
  end

  def pages_for_company(company_id)
    pages.joins(:ads)
         .where("ads.company_id=#{company_id}")
         .order("page_nr DESC")
         .uniq.pluck(:page_nr)
  end




  # Typus helper methods:

  def to_label
    "#{title} (#{date.strftime("%B")} #{date.year})"
  end
end

app/controllers/admin/issues_controller.rb
class Admin::IssuesController < Admin::ResourcesController
end

app/controllers/api/issues_controller.rb
class Api::IssuesController < Api::BaseController

  expose(:new_issue) {
    # We get back a string from the client when posting an issue because
    # of the way the request is constructed; so parse it into JSON and
    # put it back into the params hash:
    if params[:issue].is_a? String
      params[:issue] = ActiveSupport::JSON.decode(params[:issue])
    end

    Issue.new(params[:issue])
  }

  # /api/issues.json
  #   with body {"issue":{"title":"apissu","date":"2013/11/30"}}
  def create
    accept_only_json do
      if new_issue.save
        send_json_data({ issue_id: new_issue.id }, 200)
      else
        send_error_messages new_issue
      end
    end
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  expose(:current_issue) { Issue.where(id: params[:id]).first || Issue.latest.first }

  def company_pages
    company_pages = company_id.present? ? current_issue.company_pages(company_id) : []
    render json: {pages: company_pages}
  end

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = current_issue

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.haml
= simple_form_for(@issue) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :date

  .form-actions
    = f.button :submit

app/views/issues/edit.html.haml
%h1 Editing issue

= render 'form'

= link_to 'Show', @issue
\|
= link_to 'Back', issues_path

app/views/issues/index.html.haml
%h1 Listing issues

%table
  %tr
    %th Title
    %th Date
    %th

  - @issues.each do |issue|
    %tr
      %td= issue.title
      %td= issue.date
      %td= link_to 'Show', issue


#magazine
  %div{:style => "background-image:url(/assets/page_pics/01.jpg);"}
  %div{:style => "background-image:url(/assets/page_pics/02.jpg);"}
  %div{:style => "background-image:url(/assets/page_pics/03.jpg);"}
  %div{:style => "background-image:url(/assets/page_pics/04.jpg);"}
  %div{:style => "background-image:url(/assets/page_pics/05.jpg);"}
  %div{:style => "background-image:url(/assets/page_pics/06.jpg);"}
</div>


:javascript
  $(window).ready(function() {
    $('#magazine').turn({
      display: 'double',
      acceleration: true,
      gradients: !$.isTouch,
      elevation:50,
      when: {
        turned: function(e, page) {
          console.log('Current view: ', $(this).turn('view'));
        }
      }
    });
  });

  $(window).bind('keydown', function(e){

    if (e.keyCode==37)
      $('#magazine').turn('previous');
    else if (e.keyCode==39)
      $('#magazine').turn('next');

  });

app/views/issues/new.html.haml
%h1 New issue

= render 'form'

= link_to 'Back', issues_path

app/views/issues/show.html.haml
%p#notice= notice


%section#filters
  .home-link= link_to 'Nguoi Dep', root_path

  .select_issue.filter
    = label_tag :select_id, "Select issue:"
    = select_tag :issue_id, options_for_select(Issue.all_issues_with_id, @issue.id)

  .select_page.filter
    = label_tag :page_nr, "Select page:"
    = select_tag(:page_nr, options_for_select((1..@issue.pages.size).to_a) )

#magazine_container
  #magazine
    - @issue.first_pages.each do |page|
      %div{ :style => "background-image:url(#{page.url});", :class => "hard" }

  .page_nr_left.page_nr
  .turn_page.turn_page_left= link_to "<"
  .page_nr_right.page_nr
  .turn_page.turn_page_right= link_to ">"

  #zoomer
    %img
    .close
      = link_to 'close', class: 'button'

:javascript
  $(window).ready(function() {

    $("#company_id").change( function(event) {
      var company_id = $("#company_id option:selected").val()
      var pages_list = $("#companies ul.pages")
      if (company_id == 0) {
        pages_list.empty()
        return
      }

      var url = "/issues/#{@issue.id}/pages.json?company_id=" + company_id
      $.getJSON(url, function(response, status, xhr) {
        pages_list.empty()
        if (status=="success") {
          $.each(response.pages, function(key, val) {
            pages_list.append('<li><a href="#">' + val + '<a/></li>')
          })
          pages_list.find('li a').click( function(event){
            var page_nr = $(this).text()
            $("#magazine").turn("page", page_nr);
          })
        }
        else {
          pages_list.append('<li>error retrieving pages</li>')
        }
      })
    })

    function addPage(page, book) {
      // check if the page is already in the book
      if (!book.turn('hasPage', page)) {
        // Create an element for this page
        var element = $('<div />', {'class': 'page '+((page%2==0) ? 'odd' : 'even'), 'id': 'page-'+page}).html('<i class="loader"></i>');
        var url = "/issues/#{@issue.id}/pages/" + page + ".json"
        $.getJSON(url, function(response, status, xhr) {
          if (status == "error") {
            element.html('<i class="error">Error loading the next page.</i>')
            book.turn('addPage', element, page); // add element to book
          }
          else if (response != "eoi" /* end of magazine */ ) {
            element.css("background-image", "url(" + response.image + ")")
            book.turn('addPage', element, page); // add element to book
          }
        });
      }
    }

    $('#magazine').turn({
      display: 'double',
      pages: "#{@issue.pages.size}",
      acceleration: true,
      gradients: !$.isTouch,
      elevation:50,
      when: {
        turning: function(e, page, view) {
          update_page_controls(view)
          zoom_off();
          // Gets the range of pages that the book needs right now
          var range = $(this).turn('range', page);
          // Check if each page is within the book
          for (p = range[0]; p<=range[1]; p++)
              addPage(p, $(this));
        },
      }
    });
  });

  $(window).bind('keydown', function(e){
    if (e.keyCode==37)
      $('#magazine').turn('previous');
    else if (e.keyCode==39)
      $('#magazine').turn('next');
  });

  function update_page_controls(current_pages){
    var left_page = current_pages[0]
    var right_page = current_pages[1]
    $("#page_nr").val()
    if (left_page > 0){
      $(".page_nr_left").text(left_page).show()
      $(".turn_page_left").show()
    }
    else {
      $(".page_nr_left").hide()
      $(".turn_page_left").hide()
    }
    if (right_page > 0)
      $(".page_nr_right").text(right_page).show()
    else
      $(".page_nr_right").hide()
    var last_page = $(this).turn("pages")
    if (left_page == last_page || right_page == last_page)
      $(".turn_page_right").hide();
    else
      $(".turn_page_right").show();
  }

  var page_corner = new function(){
    this.magazine_left  = $('#magazine').offset().left;
    this.magazine_top   = $('#magazine').offset().top
    this.magazine_width = $('#magazine').width();
    this.magazine_height= $('#magazine').height();
    this.triangle_width = 60;   // that's about the corner size
    this.isActive = function(event) {
      var position = this.getPositionRelativeToMagazine(event.pageX, event.pageY)
      var inCorner = this.isPositionInCorner(position)
      return inCorner;
    };
    this.getPositionRelativeToMagazine = function(x, y){
      return {left: x - this.magazine_left,
              top:  y - this.magazine_top}
    }
    this.isPositionInCorner = function(pos){
      var maxTop = maxLeft = this.triangle_width;
      var maxRight = this.magazine_width - this.triangle_width;
      var maxBottom = this.magazine_height - this.triangle_width;
      return (pos.left < maxLeft && pos.top < maxTop)    ||    // top left
             (pos.left > maxRight && pos.top < maxTop)   ||    // top right
             (pos.left < maxLeft && pos.top > maxBottom) ||    // bottom left
             (pos.left > maxRight && pos.top > maxBottom)      // bottom right
    }
  }

  $('#magazine').on('click', '.turn-page-wrapper', function(e) {
     console.log('turn-page-wrapper click: page_corner.isActive(e): ' + page_corner.isActive(e));
     if (page_corner.isActive(e)) {
       e.stopImmediatePropagation();
       return;
     }
     var src, url;
     var url = $(this).find('.turn-page').css('background-image');
     var src = url.replace('url(', '').replace(')', '').replace(/"/g, '');    // a hack!
     zoom_on();
     $('#zoomer img').attr('src', src);
     set_position_close_div();
   });

  function set_position_close_div() {
    var zoomer = $('#zoomer');
    var close_div = zoomer.find('.close');
    var top = zoomer.offset().top;
    var left = zoomer.offset().left + zoomer.width() - close_div.width() - 20;
    close_div.css('top', top).css('left', left);
  }

  function zoom_on() {
    $('#magazine').hide();
    return $('#zoomer').show();
  };

  function zoom_off() {
    $('#zoomer').hide();
    return $('#magazine').show();
  };

  $('#zoomer').on('click', '.close a', function(e){
    var page_nr = $("#magazine").turn("page", page_nr);
    zoom_off();
    return false;
  })

  $('#magazine').mouseover(function(e){
    if (page_corner.isActive(e)){
      $('#magazine').removeClass('zoom_in');
      return;
    }
    $('#magazine').addClass('zoom_in');
  })
  .mouseout(function(){
    $('#magazine').removeClass('zoom_in');
  })