config/routes.rb
Nguoidep::Application.routes.draw do

  resources :issues, only: [:show], constraints: {id: /[0-9]+/} do
    scope :format => true, :constraints => { :format => 'json' } do
      resources :pages, only: [:index, :show], constraints: {id: /[0-9]+/}
    end
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
             controllers: {
                 :registrations => "registrations",
                 :confirmations => "confirmations",
                 :passwords => "passwords"
             }

  #devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
  #                   controllers: {:registrations => "registrations"}

  Devise.router_name = :main_app

  root to: 'home#index'
  get "/contact",     to: "home#contact"
  get "/advertising", to: "home#advertising"

  #resque_constraint = lambda do |request|
  #  request.env['warden'].authenticate? and request.env['warden'].user.role? :admin
  #end

  #constraints resque_constraint do
  #  mount Resque::Server, :at => "/admin/jobs"
  #end

  namespace :admin do
    resources :users

    resources :issues do
      resources :pages
    end

    resources :companies
  end

  #get :admin, to: "admin/authentications#index"

  namespace :api do
    resources :issues, constraints: {id: /[0-9]+/},    defaults: { format: 'json' }
    resources :pages, only: [:create, :show, :update], defaults: { format: 'json' }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def contact
  end

  def advertising
  end

end

app/views/home/advertising.html.haml
.home-link= link_to 'Nguoi Dep', root_path

%header
  %h1 Advertising

#section
  %p
    Nguoi Dep Magazine is a monthly Vietnamese magazine with 4,500 issues
    for FREE distribution, covering World News, US-World News, US News, Vietnam
    News, Health, Education, Life (Doi Song), Science & Technology (Khoa Hoc &
    Doi Song), Medical, History, Entertainment / Hollywood, Stories, Poems,
    Horoscope, Travel, Cooking, Ads & Classified, Vietnamese Business Directory.<br/>
    Distributed in New York, New Jersey, and Connecticut.

  %h2 Prices for Regular Black & White Ads on Newsprint
  %p All ads must be pre-paid in full.
  %table#prices
    %thead
      %tr
        %th
        %th 1 month
        %th 3 months
        %th 6 months
        %th 12 months
        %th
    %tbody
      %tr
        %th 1 page (9-1/2" x 13-1/4")
        %td $200
        %td $540
        %td $1000
        %td $1800
        %td.note{rowspan: 4}
          All first time clients<br/>
          are required<br/>
          to 3 month-contract
      %tr
        %th 1/2 page (9-1/2" x 6-1/2" or 4-5/8" x 13-1/4")
        %td $100
        %td $270
        %td $500
        %td $900
      %tr
        %th 1/4 page (4-5/8" x 6-1/2")
        %td $50
        %td $140
        %td $260
        %td $500
      %tr
        %th 1/8 page (4-5/8" x 3-1/8")
        %td $35
        %td $95
        %td $170
        %td $310
      %tr
        %th 1/16 page (2-1/4" x 3-1/8")
        %td $25
        %td $65
        %td $110
        %td $200
        %td.note For Classified Ads ONLY

  %p
    For a complete advertisement price list, please call (718) 343-4580.

  %h2 Important Notes
  %ul
    %li
      All new black & white regular ads clients must agree at least to the
      first 3-month contract.
    %li
      Regular new clients for full-color ads on glossy
      paper must agree to at least 3-month contract or on certain terms.
    %li
      The bill must be pre-paid in full.<br/>
      Please call if you have any questions.
    %li
      Deadline for classified ads and fees is on the 18th of the month.
    %li
      Ads will not be placed if payment is not received on time.
    %li
      Ads clients are recommended to contact Nguoi Dep Magazine 2-3
      days after they have sent out their ads and fee to make sure that Nguoi
      Dep Magazine has received them.

  %p
    %span.important Contents:
    Nguoi Dep Magazine will not be responsible for the contents of
    any advertisements. Nguoi Dep Magazine also has the rights to edit any
    wordings of ads, news, stories, poems, … to serve better for all readers.

app/views/home/contact.html.haml
.home-link= link_to 'Nguoi Dep', root_path

%header
  %h1 Contact

%section
  %h2 Điện Thoại và Thư Điện Tử | Telephone and Email

  %table
    %tr
      %td Cell:
      %td (917) 435-5133 Phi (speaks Vietnamese & English)
    %tr
      %td Cell:
      %td (973) 559-9321 Kiều (speaks Vietnamese)
    %tr
      %td Tel:
      %td (718) 343-4580 Duke / anh Như
    %tr
      %td Fax:
      %td (718) 343-4352
    %tr
      %td Email:
      %td nguoidepmagazine[at]yahoo.com

  %h2 Địa Chỉ | Postal Address

  %p
    NGUOI DEP MAGAZINE <br/>
    P.O. Box 10 <br/>
    Floral Park, NY 11002-0010

app/views/home/index.html.haml
%header.home
  #left_image_box
    =image_tag 'liberty460.jpg'
  .box
    %p Welcome to
    %h1 Người Đẹp Magazine, Inc.

#right_image_box
  =image_tag 'nyc.jpg'

%section.home
  .menu
    .box
      %p.viet= link_to 'Tạp Chí',         issue_path(Issue.latest.first)
      %p.engl= link_to 'Magazine Issues', issue_path(Issue.latest.first)
    .box
      %p.viet= link_to 'Liên Lạc', "/contact"
      %p.engl= link_to 'Contact', "/contact"
    .box
      %p.viet= link_to 'Đăng Quảng Cáo', "advertising"
      %p.engl= link_to 'Advertising Information', "advertising"

  .content
    .box
      %p.viet
        Người Đẹp Magazine, thành lập từ năm 1999, là Việt báo tháng phát
        hành miễn phí tổng cộng 4,500 cuốn trong tiểu bang New York,
        New Jersey, và Connecticut, có những bài vở đặc biệt của mỗi tháng,
        tin tức vòng quanh thế giới, bài vở về gia đình con cái và tình
        yêu hạnh phúc, thế giới nghệ sĩ/ người đẹp/ thời trang, truyện
        ngắn/ truyện dài, di trú, tử vi, tìm bạn bốn phương...

      %p.engl
        Nguoi Dep Magazine is a monthly Vietnamese magazine, established
        since 1999, with total of 4,500 issues for FREE distribution in
        New York, New Jersey, & Connecticut, covered important stories/articles
        and news around the world, articles on family & education and tips,
        stars/models/fashions, short & long stories, immigration,
        horoscope, section finding a friend...